version: '2'
services:
  risingarjun-app:
    image: risingarjun
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://risingarjun-mariadb:3306/risingarjun
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  risingarjun-mariadb:
    extends:
      file: mariadb.yml
      service: risingarjun-mariadb
